package com.uranium.gitlist

import com.uranium.gitlist.main.domain.model.GitRepository

internal object RepositoriesListFragmentStub {
    val repositoriesList = listOf(
        GitRepository(
            id = 5152285,
            name = "okhttp",
            starsQtd = 43013,
            forkQtd = 8951,
            authorName = "square",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 3432266,
            name = "kotlin",
            starsQtd = 42876,
            forkQtd = 5293,
            authorName = "JetBrains",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 51148780,
            name = "architecture-samples",
            starsQtd = 41622,
            forkQtd = 11299,
            authorName = "Android",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 7190986,
            name = "shadowsocks-android",
            starsQtd = 32960,
            forkQtd = 11596,
            authorName = "shadowsocks",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 95189138,
            name = "p3c",
            starsQtd = 28319,
            forkQtd = 7764,
            authorName = "alibaba",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 34824499,
            name = "leakcanary",
            starsQtd = 27934,
            forkQtd = 3907,
            authorName = "square",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 29219243,
            name = "fanqiang",
            starsQtd = 27068,
            forkQtd = 5820,
            authorName = "bannedbook",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 90792131,
            name = "architecture-components-samples",
            starsQtd = 22282,
            forkQtd = 8212,
            authorName = "android",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 18347476,
            name = "iosched",
            starsQtd = 21655,
            forkQtd = 6280,
            authorName = "google",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
        GitRepository(
            id = 26102180,
            name = "material-dialogs",
            starsQtd = 19412,
            forkQtd = 3154,
            authorName = "afollestad",
            avatarUrl = "",
            fullName = "full name",
            description = "description",
            url = "",
        ),
    )
}